;Exercise 1.9: Each of the following two procedures defines a method for adding two positive integers in terms of the procedures inc, which increments its argument by 1, and dec, which decrements its argument by 1.

(define (add a b)
  (if (= a 0) 
    b 
    (inc (+ (dec a) b))))

(define (+ a b)
  (if (= a 0) 
    b 
    (+ (dec a) (inc b))))

;Using the substitution model, illustrate the process generated by each procedure in evaluating (+ 4 5). Are these processes iterative or recursive?

;*****************                                 	
;First REPL 

1 ]=> 

(define (inc a)
  (+ a 1))

(define (dec a)
  (- a 1))
            

;Value: inc

1 ]=> 
;Value: dec

1 ]=> 

(define (+ a b)
  (if (= a 0) 
    b 
    (inc (+ (dec a) b))))

;Value: +

1 ]=> 

(+ 4 5)

; ∞

1 ]=> 

(define (+ a b)
  (if (= a 0) 
    b 
    (+ (dec a) (inc b))))


;Value: +

1 ]=> 

(+ 4 5)
;Aborting!: maximum recursion depth exceeded

;*************

;What happened here? 

;The first three lines of both procedures are the same, and ensure that if the first value is 0, the second value is returned. This is efficient and makes sure things happen quickly. 

(define (+ a b)
  (if = a 0)
  b
  
  ;First Procedure's last line is where things get strange. 
  
  (inc (+ (dec a) b)))

;This expands to
(+ (+ (- a 1) b) 1)

;Using the substitution model, the procedure will evolve as follows if the following values are input. 

(+ 4 5)

(+ (+ (- 4 1) 5) 1)
(+ (+ 3 5) 1)
(+ (8) 1)
;Value 9

;Yet this is not what is returned... instead i get ∞
;What am I missing here? 

;ITS A RECURSIVE DEFINITION!!! 
;OOOHHHHHH

(+ 4 5)

(+ (+ (- 4 1) 5) 1)
(+ (+ 3 5) 1)
(+ (+ (+ (- 3 1) 5) 1) 1)
(+ (+ (+ 2 5) 1) 1)
(+ (+ (+ (+ (- 2 1) 5) 1) 1) 1) 
(+ (+ (+ (+ 1 5) 1) 1) 1) 
(+ (+ (+ (+ (+ (- 1 1) 5) 1) 1) 1) 1)
(+ (+ (+ (+ (+ 0 5) 1) 1) 1) 1)
(+ (+ (+ (+ 5 1) 1) 1) 1)
(+ (+ (+ (+ (+ (- 5 1) 1) 1) 1) 1) 1)
(+ (+ (+ (+ (+ 4 1) 1) 1) 1) 1)
(+ (+ (+ (+ (+ (+ 4 1) 1) 1) 1) 1) 1)
   
;I THINK EVEN THIS IS WRONG. I THINK IT GOES EVEN DEEPER HERE.
;The call to inc calls another + which adds another layer of addition to the call. 
;Wow this adds onto it self quickly. 
;Lets build this one out. 
   
(+ 4 5)
;a != 0 so it returns line 4

(inc (+ (dec 4) 5))
;with dec expanded
(inc (+ (- 4 1) 5))
;with inc expanded
(+ (+ (- 4 1) 5) 1)
;(- 4 1) solved
(+ (+ 3 5) 1)
;(+ 3 5) expanded
(+ (inc (+ (dec 3) 5)) 1)
;with dec expanded
(+ (inc (+ (- 3 1) 5)) 1)
;with inc expanded
(+ (+ (+ (- 3 1) 5) 1) 1)
;(- 3 1)solved
(+ (+ (+ 2 5) 1) 1)
;(+ 2 5) expanded
(+ (+ (inc (+ (dec 2) 5)) 1) 1)
;dec expanded
(+ (+ (inc (+ (- 2 1) 5)) 1) 1)
;inc expanded
(+ (+ (+ (+ (- 2 1) 5) 1) 1) 1)
;(- 2 1) solved
(+ (+ (+ (+ 1 5) 1) 1) 1)
;(+ 1 5) expanded
(+ (+ (+ (inc (+ (dec 1) 5)) 1) 1) 1)
;dec expanded
(+ (+ (+ (inc (+ (- 1 1) 5)) 1) 1) 1)
;inc expanded
(+ (+ (+ (+ (+ (- 1 1) 5) 1) 1) 1) 1)
;(- 1 1) solved
(+ (+ (+ (+ (+ 0 5) 1) 1) 1) 1)
;b!!!
(+ (+ (+ (+ 5 1) 1) 1) 1)
;(+ 5 1)expanded
(+ (+ (+ (inc (+ (dec 5) 1)) 1) 1) 1)
;dec expanded
(+ (+ (+ (inc (+ (- 5 1) 1)) 1) 1) 1)
;inc expanded
(+ (+ (+ (+ (+ (- 5 1) 1) 1) 1) 1) 1)
;(- 5 1) solved
(+ (+ (+ (+ (+ 4 1) 1) 1) 1) 1)
;(+ 4 1) expanded
(+ (+ (+ (+ (inc (+ (dec 4) 1)) 1) 1) 1) 1)
;dec expanded
(+ (+ (+ (+ (inc (+ (- 4 1) 1)) 1) 1) 1) 1)
;inc expanded
(+ (+ (+ (+ (+ (+ (- 4 1) 1) 1) 1) 1) 1) 1)
;(- 4 1) solved
(+ (+ (+ (+ (+ (+ 3 1) 1) 1) 1) 1) 1)
;(+ 3 1) expanded
(+ (+ (+ (+ (+ (inc (+ (dec 3) 1)) 1) 1) 1) 1) 1)
;dec expanded
(+ (+ (+ (+ (+ (inc (+ (- 3 1) 1)) 1) 1) 1) 1) 1)
;inc expanded
(+ (+ (+ (+ (+ (+ (+ (- 3 1) 1) 1) 1) 1) 1) 1) 1)
;(- 3 1) solved
(+ (+ (+ (+ (+ (+ (+ 2 1) 1) 1) 1) 1) 1) 1)
;+ 2 1 expanded
(+ (+ (+ (+ (+ (+ (inc (+ (dec 2) 1)) 1) 1) 1) 1) 1) 1)
;dec expanded
(+ (+ (+ (+ (+ (+ (inc (+ (- 2 1) 1)) 1) 1) 1) 1) 1) 1)
;inc expanded
(+ (+ (+ (+ (+ (+ (+ (+ (- 2 1) 1) 1) 1) 1) 1) 1) 1) 1)
;(- 2 1) solved
(+ (+ (+ (+ (+ (+ (+ (+ 1 1) 1) 1) 1) 1) 1) 1) 1)
;(+ 1 1) expanded
(+ (+ (+ (+ (+ (+ (+ (inc (+ (dec 1) 1)) 1) 1) 1) 1) 1) 1) 1)
;dec expanded
(+ (+ (+ (+ (+ (+ (+ (inc (+ (- 1 1) 1)) 1) 1) 1) 1) 1) 1) 1)
;inc expanded
(+ (+ (+ (+ (+ (+ (+ (+ (+ (- 1 1) 1) 1) 1) 1) 1) 1) 1) 1) 1)
;(- 1 1) solved
(+ (+ (+ (+ (+ (+ (+ (+ (+ 0 1) 1) 1) 1) 1) 1) 1) 1) 1)
;b!!!
(+ (+ (+ (+ (+ (+ (+ (+ 1 1) 1) 1) 1) 1) 1) 1) 1)
;This reduces down to 9.


;This was dumb. I could have written this without expanding inc every time. Sigh.  


(+ 4 5) 
 (inc (+ (dec 4) 5)) 
 (inc (+ 3 5)) 
 (inc (inc (+ (dec 3) 5))) 
 (inc (inc (+ 2 5))) 
 (inc (inc (inc (+ (dec 2) 5)))) 
 (inc (inc (inc (+ 1 5)))) 
 (inc (inc (inc (inc (+ (dec 1) 5))))) 
 (inc (inc (inc (inc (+ 0 5))))) 
 (inc (inc (inc (inc 5)))) 
 (inc (inc (inc 6))) 
 (inc (inc 7)) 
 (inc 8) 
  
 9 

;PROCEDURE 2










                                                                                                                                                            